/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFComunidades.java
 *
 * Created on 09/04/2011, 00:52:43
 */

package sgfi;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import sgfi.Classes.ClassConecta;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import sgfi.Classes.Comunidade;
import sgfi.Classes.Funcoes;

/**
 *
 * @author vitiazze
 */
public class jFComunidades extends javax.swing.JFrame {

    /** Creates new form jFComunidades */
    public jFComunidades() {
        initComponents();
        JRootPane meurootpane = getRootPane();
        meurootpane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        meurootpane.getRootPane().getActionMap().put("ESCAPE", new AbstractAction("ESCAPE") {

            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        SairjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeComunidadejTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codComunidadejSpinner = new javax.swing.JSpinner();
        nomeComunidadejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnpjjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        insc_EstadualjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enderecojTextField = new javax.swing.JTextField();
        bairrojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ufjComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cepjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        telefone1jFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        telefone2jFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observacaojTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sgfi.SGFIApp.class).getContext().getResourceMap(jFComunidades.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        buscarjButton.setIcon(resourceMap.getIcon("buscarjButton.icon")); // NOI18N
        buscarjButton.setText(resourceMap.getString("buscarjButton.text")); // NOI18N
        buscarjButton.setToolTipText(resourceMap.getString("buscarjButton.toolTipText")); // NOI18N
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setName("buscarjButton"); // NOI18N
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(resourceMap.getIcon("novojButton.icon")); // NOI18N
        novojButton.setText(resourceMap.getString("novojButton.text")); // NOI18N
        novojButton.setToolTipText(resourceMap.getString("novojButton.toolTipText")); // NOI18N
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setName("novojButton"); // NOI18N
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setIcon(resourceMap.getIcon("editarjButton.icon")); // NOI18N
        editarjButton.setText(resourceMap.getString("editarjButton.text")); // NOI18N
        editarjButton.setToolTipText(resourceMap.getString("editarjButton.toolTipText")); // NOI18N
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setName("editarjButton"); // NOI18N
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setIcon(resourceMap.getIcon("salvarjButton.icon")); // NOI18N
        salvarjButton.setText(resourceMap.getString("salvarjButton.text")); // NOI18N
        salvarjButton.setToolTipText(resourceMap.getString("salvarjButton.toolTipText")); // NOI18N
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setName("salvarjButton"); // NOI18N
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        alterarjButton.setIcon(resourceMap.getIcon("alterarjButton.icon")); // NOI18N
        alterarjButton.setText(resourceMap.getString("alterarjButton.text")); // NOI18N
        alterarjButton.setToolTipText(resourceMap.getString("alterarjButton.toolTipText")); // NOI18N
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setName("alterarjButton"); // NOI18N
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(resourceMap.getIcon("excluirjButton.icon")); // NOI18N
        excluirjButton.setText(resourceMap.getString("excluirjButton.text")); // NOI18N
        excluirjButton.setToolTipText(resourceMap.getString("excluirjButton.toolTipText")); // NOI18N
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setName("excluirjButton"); // NOI18N
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);

        SairjButton.setIcon(resourceMap.getIcon("SairjButton.icon")); // NOI18N
        SairjButton.setText(resourceMap.getString("SairjButton.text")); // NOI18N
        SairjButton.setToolTipText(resourceMap.getString("SairjButton.toolTipText")); // NOI18N
        SairjButton.setFocusable(false);
        SairjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SairjButton.setName("SairjButton"); // NOI18N
        SairjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(SairjButton);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gradeComunidadejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Comunidade", "Endereço", "Telefone 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gradeComunidadejTable.setName("gradeComunidadejTable"); // NOI18N
        gradeComunidadejTable.getTableHeader().setReorderingAllowed(false);
        gradeComunidadejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeComunidadejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeComunidadejTable);
        gradeComunidadejTable.getColumnModel().getColumn(0).setResizable(false);
        gradeComunidadejTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        gradeComunidadejTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("gradeComunidadejTable.columnModel.title0")); // NOI18N
        gradeComunidadejTable.getColumnModel().getColumn(1).setResizable(false);
        gradeComunidadejTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeComunidadejTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("gradeComunidadejTable.columnModel.title1")); // NOI18N
        gradeComunidadejTable.getColumnModel().getColumn(2).setResizable(false);
        gradeComunidadejTable.getColumnModel().getColumn(2).setPreferredWidth(300);
        gradeComunidadejTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("gradeComunidadejTable.columnModel.title2")); // NOI18N
        gradeComunidadejTable.getColumnModel().getColumn(3).setResizable(false);
        gradeComunidadejTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        gradeComunidadejTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("gradeComunidadejTable.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        codComunidadejSpinner.setName("codComunidadejSpinner"); // NOI18N

        nomeComunidadejTextField.setText(resourceMap.getString("nomeComunidadejTextField.text")); // NOI18N
        nomeComunidadejTextField.setName("nomeComunidadejTextField"); // NOI18N
        nomeComunidadejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeComunidadejTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        try {
            cnpjjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpjjFormattedTextField.setName("cnpjjFormattedTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        insc_EstadualjTextField.setText(resourceMap.getString("insc_EstadualjTextField.text")); // NOI18N
        insc_EstadualjTextField.setName("insc_EstadualjTextField"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        enderecojTextField.setText(resourceMap.getString("enderecojTextField.text")); // NOI18N
        enderecojTextField.setName("enderecojTextField"); // NOI18N

        bairrojTextField.setText(resourceMap.getString("bairrojTextField.text")); // NOI18N
        bairrojTextField.setName("bairrojTextField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        cidadejTextField.setText(resourceMap.getString("cidadejTextField.text")); // NOI18N
        cidadejTextField.setName("cidadejTextField"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        ufjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        ufjComboBox.setName("ufjComboBox"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        try {
            cepjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepjFormattedTextField.setName("cepjFormattedTextField"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        try {
            telefone1jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone1jFormattedTextField.setName("telefone1jFormattedTextField"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        try {
            telefone2jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone2jFormattedTextField.setName("telefone2jFormattedTextField"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        emailjTextField.setText(resourceMap.getString("emailjTextField.text")); // NOI18N
        emailjTextField.setName("emailjTextField"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        observacaojTextArea.setColumns(20);
        observacaojTextArea.setRows(5);
        observacaojTextArea.setName("observacaojTextArea"); // NOI18N
        observacaojTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                observacaojTextAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(observacaojTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(659, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(codComunidadejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeComunidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(bairrojTextField))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cnpjjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(insc_EstadualjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefone1jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefone2jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(emailjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))))
                        .addGap(45, 45, 45))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cepjFormattedTextField, cidadejTextField, cnpjjFormattedTextField, insc_EstadualjTextField, telefone1jFormattedTextField, telefone2jFormattedTextField});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codComunidadejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeComunidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insc_EstadualjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone1jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone2jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ClassConecta conexao = new ClassConecta();

    public int codComunidade;


      public void getGrandeComunidade() throws ParseException{
       //Consultar pedidos
        Comunidade oComunidade = new Comunidade();

        if ( nomeComunidadejTextField.getText().length() > 0 ){
            oComunidade.setNomeComunidade(nomeComunidadejTextField.getText()+"%");
        }

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Código", "Comunidade", "Endereço", "Telefone 1"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeComunidadejTable.setModel(modeloTabela);
        gradeComunidadejTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        gradeComunidadejTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeComunidadejTable.getColumnModel().getColumn(2).setPreferredWidth(300);
        gradeComunidadejTable.getColumnModel().getColumn(3).setPreferredWidth(100);



try {
            resultSet = oComunidade.getConsultar();
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(Comunidade.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("codComunidade")),
                    resultSet.getString("nomeComunidade"),
                    resultSet.getString("endereco") + " " + ","+" "+ resultSet.getString("bairro")+ " " + ","+" "+ resultSet.getString("Cidade")
                    + " " + "-"+" "+ resultSet.getString("uf") ,
                    resultSet.getString("telefone1"),
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(Comunidade.class.getName()).log(Level.SEVERE, null, ex);
        }

           }

    private void SairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairjButtonActionPerformed
        // TODO add your handling code here:
        if (salvarjButton.isEnabled()){
            Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Deseja realmente Sair sem salvar?\nAs informações não salvas serão perdidas!",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }
        this.dispose();

        }else{
            this.dispose();
        }

}//GEN-LAST:event_SairjButtonActionPerformed

    public void getFieldComunidade(int codComunidade) throws ParseException{

        Comunidade oComunidade = new Comunidade();
        ResultSet rs = null;
        oComunidade.setCodComunidade(codComunidade);

        try {
            rs = oComunidade.getConsultar();
            rs.next();

            //Pegar campos
            codComunidadejSpinner.setValue(rs.getInt("codComunidade"));
            nomeComunidadejTextField.setText(rs.getString("nomeComunidade"));
            cnpjjFormattedTextField.setText(rs.getString("cnpj"));
            insc_EstadualjTextField.setText(rs.getString("insc_Estadual"));
            enderecojTextField.setText(rs.getString("endereco"));
            bairrojTextField.setText(rs.getString("bairro"));
            cidadejTextField.setText(rs.getString("cidade"));
            cepjFormattedTextField.setText(rs.getString("cep"));
            ufjComboBox.setSelectedItem(rs.getString("uf"));
            telefone1jFormattedTextField.setText(rs.getString("telefone1"));
            telefone2jFormattedTextField.setText(rs.getString("telefone2"));
            emailjTextField.setText(rs.getString("email"));
            observacaojTextArea.setText(rs.getString("observacao"));

        } catch (SQLException ex) {
            Logger.getLogger(Comunidade.class.getName()).log(Level.SEVERE, null, ex);
        }



    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                ClassConecta.conecta();
                buscarjButtonActionPerformed(null);



                nomeComunidadejTextField.grabFocus();
                ufjComboBox.setSelectedItem("ES");

                    salvarjButton.setEnabled(false);
                    alterarjButton.setEnabled(false);
                    excluirjButton.setEnabled(false);
                    editarjButton.setEnabled(false);
                    novojButton.setEnabled(true);

    }//GEN-LAST:event_formWindowOpened

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        Comunidade oComunidade = new Comunidade();
        // Verifica se o campo Nome da igreja ou comunidade esta preechido
        if(nomeComunidadejTextField.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Preencha o campo: Nome da Igreja ou Comunidade.", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
           // Se o campo nome da igreja estiver preencido conferir o campo UF
        }else if(ufjComboBox.getSelectedItem().equals("...")){

            JOptionPane.showMessageDialog(null, "Preencha o campo: UF.", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);

        }else{
            try {
                salvarjButton.setEnabled(false);
                alterarjButton.setEnabled(false);
                excluirjButton.setEnabled(false);
                editarjButton.setEnabled(false);
                novojButton.setEnabled(true);
                oComunidade.setNomeComunidade(nomeComunidadejTextField.getText());
                oComunidade.setCnpj(cnpjjFormattedTextField.getText());
                oComunidade.setInsc_Estadual(insc_EstadualjTextField.getText());
                oComunidade.setEndereco(enderecojTextField.getText());
                oComunidade.setBairro(bairrojTextField.getText());
                oComunidade.setCidade(cidadejTextField.getText());
                oComunidade.setCep(cepjFormattedTextField.getText());
                oComunidade.setUf((String) ufjComboBox.getSelectedItem());
                oComunidade.setTelefone1(telefone1jFormattedTextField.getText());
                oComunidade.setTelefone2(telefone2jFormattedTextField.getText());
                oComunidade.setEmail(emailjTextField.getText());
                oComunidade.setObervacao(observacaojTextArea.getText());

                
                
                oComunidade.setCadastrar();
                try {
                    ClassConecta.con.commit();
                    ClassConecta.con.setAutoCommit(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    getGrandeComunidade();
                    int cod_Comunidade = oComunidade.getId();
                    Funcoes.getItemJTable(cod_Comunidade, gradeComunidadejTable);
                } catch (ParseException ex) {
                    Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

                        
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        try {
            getGrandeComunidade();
        } catch (ParseException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        try {
            // TODO add your handling code here:
            novojButton.setEnabled(false);
            salvarjButton.setEnabled(false);
            editarjButton.setEnabled(false);
            alterarjButton.setEnabled(true);
            excluirjButton.setEnabled(true);
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void gradeComunidadejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeComunidadejTableMouseClicked
        try {
            // TODO add your handling code here:
            editarjButton.setEnabled(true);
            codComunidade = Integer.parseInt(gradeComunidadejTable.getValueAt(gradeComunidadejTable.getSelectedRow(), 0).toString());
            if (codComunidade == 0) {
                return;
            }
            getFieldComunidade(codComunidade);
        } catch (ParseException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gradeComunidadejTableMouseClicked

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:

        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);
        @SuppressWarnings("LocalVariableHidesMemberVariable")
        int codComunidade = 0;
        codComunidade = Integer.parseInt(gradeComunidadejTable.getValueAt(gradeComunidadejTable.getSelectedRow(), 0).toString());

        Comunidade oComunidade = new Comunidade();

       oComunidade.setCodComunidade(codComunidade);
        oComunidade.setNomeComunidade(nomeComunidadejTextField.getText());
        oComunidade.setCnpj(cnpjjFormattedTextField.getText());
        oComunidade.setInsc_Estadual(insc_EstadualjTextField.getText());
        oComunidade.setEndereco(enderecojTextField.getText());
        oComunidade.setBairro(bairrojTextField.getText());
        oComunidade.setCidade(cidadejTextField.getText());
        oComunidade.setCep(cepjFormattedTextField.getText());
        oComunidade.setUf((String) ufjComboBox.getSelectedItem());
        oComunidade.setTelefone1(telefone1jFormattedTextField.getText());
        oComunidade.setTelefone2(telefone2jFormattedTextField.getText());
        oComunidade.setEmail(emailjTextField.getText());
        oComunidade.setObervacao(observacaojTextArea.getText());

       oComunidade.setAlterar(conexao);
        try {
            ClassConecta.con.commit();
            ClassConecta.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }
       try {
        Funcoes.getItemJTable(codComunidade, gradeComunidadejTable);
        
            getGrandeComunidade();
        } catch (ParseException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
             Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Deseja realmente EXCLUIR esta Comunidade?",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);

        int codComunidade2 = 0;
        codComunidade2 = Integer.parseInt(gradeComunidadejTable.getValueAt(gradeComunidadejTable.getSelectedRow(), 0).toString());

        Comunidade oComunidade = new Comunidade();
        oComunidade.setCodComunidade(codComunidade2);
        oComunidade.setExcluir(conexao);
        try {
            ClassConecta.con.commit();
            ClassConecta.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            nomeComunidadejTextField.setText("");
            cnpjjFormattedTextField.setText("");
            insc_EstadualjTextField.setText("");
            enderecojTextField.setText("");
            bairrojTextField.setText("");
            cidadejTextField.setText("");
            cepjFormattedTextField.setText("");
            ufjComboBox.setSelectedItem("ES");
            telefone1jFormattedTextField.setText("");
            telefone2jFormattedTextField.setText("");
            emailjTextField.setText("");
            observacaojTextArea.setText("");
            codComunidadejSpinner.setValue(0);

            getGrandeComunidade();
        } catch (ParseException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void observacaojTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_observacaojTextAreaKeyTyped
        // TODO add your handling code here:
        observacaojTextArea.setLineWrap(true);
        observacaojTextArea.setWrapStyleWord(true);
    }//GEN-LAST:event_observacaojTextAreaKeyTyped

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
            novojButton.setEnabled(false);
            alterarjButton.setEnabled(false);
            editarjButton.setEnabled(false);
            excluirjButton.setEnabled(false);
            buscarjButton.setEnabled(true);
            salvarjButton.setEnabled(true);
            codComunidadejSpinner.setEnabled(false);
            nomeComunidadejTextField.grabFocus();
        try {
            ClassConecta.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFComunidades.class.getName()).log(Level.SEVERE, null, ex);
        }

            nomeComunidadejTextField.setText("");
            cnpjjFormattedTextField.setText("");
            insc_EstadualjTextField.setText("");
            enderecojTextField.setText("");
            bairrojTextField.setText("");
            cidadejTextField.setText("");
            cepjFormattedTextField.setText("");
            ufjComboBox.setSelectedItem("ES");
            telefone1jFormattedTextField.setText("");
            telefone2jFormattedTextField.setText("");
            emailjTextField.setText("");
            observacaojTextArea.setText("");
    }//GEN-LAST:event_novojButtonActionPerformed

    private void nomeComunidadejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeComunidadejTextFieldKeyReleased
        // TODO add your handling code here:
                if (!alterarjButton.isEnabled()){
            try {
                Comunidade oComunidade = new Comunidade();
                oComunidade.setNomeComunidade(nomeComunidadejTextField.getText());
                ResultSet rs = null;
                rs = oComunidade.getConsultar();
                getGrandeComunidade();
            } catch (ParseException ex) {
                Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(jFPessoas.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
            if(nomeComunidadejTextField.getText().equals("")){
            nomeComunidadejTextField.setText("");
            enderecojTextField.setText("");
            insc_EstadualjTextField.setText("");
            bairrojTextField.setText("");
            cidadejTextField.setText("");
            ufjComboBox.setSelectedItem("ES");
            telefone1jFormattedTextField.setText("");
            telefone2jFormattedTextField.setText("");
            ufjComboBox.setSelectedItem("ES");
            emailjTextField.setText("");
            observacaojTextArea.setText("");
            cnpjjFormattedTextField.setText("");
            cepjFormattedTextField.setText("");
            codComunidadejSpinner.setValue(0);

                }
    }//GEN-LAST:event_nomeComunidadejTextFieldKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFComunidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SairjButton;
    private javax.swing.JButton alterarjButton;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JFormattedTextField cnpjjFormattedTextField;
    private javax.swing.JSpinner codComunidadejSpinner;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradeComunidadejTable;
    private javax.swing.JTextField insc_EstadualjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nomeComunidadejTextField;
    private javax.swing.JButton novojButton;
    private javax.swing.JTextArea observacaojTextArea;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JFormattedTextField telefone1jFormattedTextField;
    private javax.swing.JFormattedTextField telefone2jFormattedTextField;
    private javax.swing.JComboBox ufjComboBox;
    // End of variables declaration//GEN-END:variables

}
